package com.threatadvisor.ai.coderemediation;

public enum RemediationStrategyType {
    DEPENDENCY_UPGRADE,
    DEPENDENCY_OVERRIDE,
    TRANSITIVE_DEPENDENCY_OVERRIDE,
    BASE_IMAGE_UPGRADE,
    DOCKERFILE_CHANGE,
    KUBERNETES_CONFIGURATION_CHANGE,
    APPLICATION_CONFIGURATION_CHANGE,
    SOURCE_CODE_CHANGE,
    FRAMEWORK_UPGRADE,
    MULTI_FILE_CHANGE,
    MANUAL_REVIEW
}
